dist: xenial
language: python
python:
    - "2.7"
    - "3.7"
    - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install pytest pytest-runner pytest-benchmark

script: python setup.py test
